version: "3.9"
services:
  joinus_db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend

  backend:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - DB_HOST=joinus_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=joinus
      - JWT_SECRET=sunioj
    networks:
      - backend
    depends_on:
      - joinus_db

volumes:
  db-data:

networks:
  backend:
