version: "3.9"
services:
  joinus_db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
    ports:
      - "80:8000"
    environment:
      - DB_HOST=joinus_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=joinus
      - JWT_SECRET=sunioj
    networks:
      - backend
    depends_on:
      joinus_db:
        condition: service_healthy

volumes:
  db-data:

networks:
  backend:
