version: "3.9"
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  backend:
    build:
      context: .
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_NAME=joinus
      - JWT_SECRET=sunioj
    network_mode: host

volumes:
  db-data:
